package com.example.unsplashapp

import android.app.Application
import com.example.unsplashapp.di.UnsplashServiceLocator
import dagger.hilt.android.HiltAndroidApp

/*
The @HiltAndroidApp annotation is used to trigger Hilt's code generation, including a base class
for your application that serves as the application-level dependency container.

This generated component is attached to the Application object and provides dependencies to it.
The base class generated by Hilt implements the GeneratedComponentManagerHolder interface, which
means that activities, fragments, services, or view models that are going to use dependency injection
can access the dependency container through this interface.
*/

@HiltAndroidApp
class UnsplashApplication : Application() {
  override fun onCreate() {
    super.onCreate()
    UnsplashServiceLocator.initWith(application = this)
  }
}
